"""Build the static portfolio. Run: python3 build.py"""
import json,html
from editorial import motif, rich, prose, essay_card, essay_body
from pathlib import Path
R=Path(__file__).resolve().parent
projects=json.loads((R/'content.json').read_text());writings=json.loads((R/'writing.json').read_text())
E=html.escape
art_content=json.loads((R/'art-content.json').read_text())
ARTICLE='https://lfedge.org/how-uc-santa-cruz-students-are-using-edgelake-and-ai-to-build-a-smarter-self-sufficient-home/'
def header(prefix=''):
 return f'''<a class="skip" href="#main-content">Skip to content</a><header class="header wrap"><a class="brand" href="{prefix}index.html" aria-label="Harsh Ranjan home">harsh ranjan<span>.</span></a><nav aria-label="Main navigation"><a href="{prefix}index.html#work">Projects</a><a href="{prefix}index.html#writing">Writing</a><a href="{prefix}index.html#hobbies">Hobbies</a><a href="{prefix}index.html#experience">Experience</a><a class="cv" href="{prefix}Harsh_Ranjan_Resume.pdf" download>CV ↗</a></nav></header>'''
def footer(prefix=''):
 return f'''<section class="contact"><div class="wrap"><div><h2>Good work starts with<br><em>a good conversation.</em></h2><p>Open to new-grad opportunities in systems, embedded software and applied ML. UC Santa Cruz · graduating December 2026.</p></div><a href="mailto:ranjan.harsh22@hotmail.com">Let’s talk ↗</a></div></section><footer class="footer wrap"><span>© 2026 Harsh Ranjan · San Francisco Bay Area</span><div><a href="https://github.com/hranjan004">GitHub ↗</a><a href="{prefix}credits.html">Image credits</a><a href="{prefix}index.html#top">Back to top ↑</a></div></footer>'''
def page(title,description,body,prefix=''):
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} — Harsh Ranjan</title><meta name="description" content="{E(description,quote=True)}"><meta name="theme-color" content="#08172c"><meta property="og:title" content="{E(title,quote=True)} — Harsh Ranjan"><meta property="og:description" content="{E(description,quote=True)}"><meta property="og:type" content="website"><link rel="icon" href="{prefix}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="{prefix}styles.css?v=4"><script src="{prefix}site.js?v=4" defer></script></head><body id="top">{header(prefix)}{body}{footer(prefix)}</body></html>'''
def visual(p,prefix='',large=False):
 kind=p['visual']; inside=''
 if kind in ['solar','circuit']:
  alt='Aerial photograph of a solar array; contextual image' if kind=='solar' else 'Close-up of a circuit board; contextual image'
  inside=f'<img src="{prefix}assets/{kind}.webp" alt="{alt}" width="1600" height="1100" loading="lazy">'
 elif kind=='compute':inside='<div class="matrix" aria-hidden="true">'+''.join('<i></i>' for _ in range(64))+'</div>'
 elif kind=='osmosis':
  inside='<div class="game" aria-hidden="true">'+''.join(f'<i class="molecule" style="--x:{x}%;--y:{y}%;--speed:{3+i*.4}s"></i>' for i,(x,y) in enumerate([(20,20),(65,40),(30,60),(73,22),(18,45),(60,65),(35,32),(76,54)]))+'<span class="game-label">OSMOSIS / RTL GAME INTERPRETATION</span></div>'
 elif kind=='network':inside='<div class="network-map" aria-hidden="true"><div class="node"><b>↗</b>REQUEST</div><div class="node mid"><b>↔</b>SHARED STATE</div><div class="node"><b>✓</b>RESPONSE</div><i class="packet"></i></div>'
 elif kind=='agents':inside='<div class="agent-ring" aria-hidden="true"></div><div class="agent-core" aria-hidden="true">✳</div>'
 return f'<div class="cover {kind} {"page-cover" if large else ""}">{inside}<span class="cover-label">{E(p["title"])}</span><div class="cover-stat"><b>{E(p["metric"])}</b><small>{E(p["label"])}</small></div></div>'
def status(p):return '<span class="state '+p['status'].lower()+'">'+p['status']+'</span>'
def card(p):
 group='hardware' if p['id']=='osmosis' else 'systems' if p['id'] in ['gpt2-performance','caching-proxy'] else 'product' if p['id']=='tesphase' else 'ml'
 return f'''<article class="card" data-group="{group}" id="{p['id']}"><a href="projects/{p['id']}.html">{visual(p)}<div class="card-meta"><span>{E(p['category'])}</span>{status(p)}</div><h3>{E(p['headline'])}</h3><p>{E(p['summary'])}</p><div class="card-bottom"><span>{E(' / '.join(p['tools'][:3]))}</span><span class="arrow" aria-label="Read case study">↗</span></div></a></article>'''
art=[
 ('tree','The Tree and Three Acts','Photography · January 2026','Wooden sticks, stones and soil become a scene about growth and the passage of time. I arranged simple materials within a landscape and used photography to explore how a small gesture can carry a larger narrative.'),
 ('wire','Hanging by the Edge','Copper wire · February 2026','A suspended human figure made from coiled copper wire. I used an open structure and a tangled head to explore urgency, vulnerability and the cost of leaving too little time to experiment.'),
 ('crown','The Crown that Carries Memory','Wearable sculpture · February 2026','A Technoblade-inspired crown built from cardboard, paper, wire and reused ramen packaging. Its deliberately rectangular shape carries a digital memory into a physical object; the packaging provides both reinforcement and a visible record of resourcefulness.'),
 ('portrait','Self Portrait','Still-life photography · January 2026','A book, a pen and a mirror stand in for absorbing information, turning it into thought and examining the self. I used their arrangement to explore the relationship between what we take in and what we put back into the world.'),
 ('ritual','Ritual Tool','Paper lamination · February 2026','A tissue-and-glue impression of a comb turns an ordinary morning action into something visible. Reproducing its closely spaced teeth made a familiar object unexpectedly difficult, and made me look more carefully at its form.'),
 ('assemblage','Container Assemblage','Found-object assemblage','An orientation bag, a watch, a wheel and headphones become a study of arrival, time and movement. Inspired by the associations objects carry, I used the container to hold a small narrative about entering a new place.')]
roles=[
 ('Sep 2026 — Present','Research Intern · EADS','UCSC · Renewable Resilient Energy Systems Lab','Deploying and debugging AnyLog / EdgeLake infrastructure for distributed electrical anomaly detection under Dr. Pat Mantey.'),
 ('Jan — Oct 2026','Capstone Lead Engineer','UCSC · Microgrid Manager','Led the model, labeling and dashboard work for a residential energy system. Connected research decisions to a running deployment and weekly sponsor reviews.'),
 ('Fall 2025 — Present','Reader','UCSC · Applied Mathematics & Statistics','Grading, rubrics and student support across AM 10, AM 20 and STATS 5. I focus on making methods and reasoning clear.'),
 ('Apr — Sep 2025','Chief Technology Officer','Tesphase','Owned the roadmap and mobile architecture. More than 30 customer interviews informed shipped authentication, real-time sync and notifications. SC Launchpad 2025 winner.'),
 ('Jun — Sep 2024','Product Management Intern','Balat Enterprises','Translated customer feedback into React / Firebase product specifications and redesigned a customer-service tool. Reported outcomes include 40% fewer post-release bugs and a 30% retention increase.'),
 ('Jul — Aug 2022','Marketing Intern','Vyavshay Technologies','Used market research and campaign analysis to guide feature priorities for a rural mobility application, contributing to a reported 15% retention increase.')]
hero='''<section class="hero wrap fade-in"><span class="eyebrow"><i class="dot"></i>Computer engineer · builder · curious generalist</span><h1>I build systems that work<br>in the <em>real world.</em><br>And write about the world they work in.</h1><p>Edge inference. Concurrent systems. Structural RTL.<br>I’m Harsh, a computer engineering senior at UC Santa Cruz.</p><div class="hero-links"><a class="text-link" href="#work">Explore my work ↓</a><a class="text-link" href="mailto:ranjan.harsh22@hotmail.com">Get in touch ↗</a></div><div class="hero-orbit" aria-hidden="true"></div></section>'''
work='''<section class="section work wrap" id="work"><div class="section-top"><div><span class="section-number">01 / SELECTED WORK</span><h2>Built with a purpose.</h2></div><p>Problem → architecture → implementation → validation.<br>Engineering decisions, with their tradeoffs made explicit.</p></div><div class="filters" role="group" aria-label="Filter featured projects">'''+''.join(f'<button type="button" data-filter="{v}" aria-pressed="{str(v=="all").lower()}">{t}</button>' for v,t in [('all','All work'),('ml','AI & energy'),('systems','Systems'),('hardware','Hardware'),('product','Product')])+'''</div><span id="filter-status" class="sr-only" role="status" aria-live="polite"></span><div class="grid">'''+''.join(card(p) for p in projects[:6])+'''</div><details class="archive"><summary>More projects & experiments <span aria-hidden="true">↗</span></summary><div class="archive-list">'''+''.join(f'<a class="archive-link" href="projects/{p["id"]}.html"><div><strong>{E(p["title"])}</strong><small>{E(p["category"])}</small></div>{status(p)}</a>' for p in projects[6:])+'''</div></details></section>'''
featured_ids=['fire-and-fission','under-the-thumb','sources-of-law','connection-installation','royce','slug-board-reflection']
featured=[next(w for w in writings if w['id']==id) for id in featured_ids]
writing='<section class="writing-band" id="writing"><div class="section wrap"><div class="section-top"><div><span class="section-number">02 / ESSAYS & INQUIRY</span><h2>Systems. Stories. Consequences.</h2></div><p>Close readings and engineering reflections.<br>Each begins with a question worth pursuing.</p></div><div class="essay-grid">'+''.join(essay_card(w) for w in featured)+'</div><div class="writing-more"><a class="cv" href="writing/index.html">Explore all '+str(len(writings))+' essays & reflections ↗</a><a class="text-link" href="'+ARTICLE+'">Co-authored on LF Edge ↗</a></div></div></section>'
hobbies='''<section class="section wrap" id="hobbies"><div class="section-top"><div><span class="section-number">03 / OUTSIDE THE TERMINAL</span><h2>Making room for curiosity.</h2></div><p>I also make things with wire, paper and found objects. Sometimes the medium is a sentence.</p></div><div class="gallery">'''+''.join(f'<a class="art" href="art/{id}.html"><div class="art-img"><img src="assets/{id}.webp" alt="{E(title)} — original artwork by Harsh Ranjan" width="700" height="900" loading="lazy"></div><h3>{E(title)}</h3><p>{E(meta)}</p></a>' for id,title,meta,desc in art)+'''</div><div class="interests"><div><h3>On my bookshelf</h3><p>Murakami’s <em>Kafka on the Shore</em> and Vikram Chandra’s <em>Sacred Games</em> are touchstones. I’m drawn to writing that unsettles familiar ways of seeing, from Hindi literature and mythology to political economy.</p></div><div><h3>Ideas beyond engineering</h3><p>I write about democratic institutions, read myths as arguments about power, and think about cinema and memory. Studio work gives those questions another form: something I can arrange, bend, build or photograph.</p></div></div></section>'''
experience='''<section class="section experience wrap" id="experience"><div class="section-top"><div><span class="section-number">04 / EXPERIENCE</span><h2>Where I’ve contributed.</h2></div><p>Engineering, product thinking and the work<br>of making complex ideas understandable.</p></div><div class="roles">'''+''.join(f'<article class="role"><time>{date}</time><div><h3>{E(title)}</h3><p class="org">{E(org)}</p></div><p>{E(desc)}</p></article>' for date,title,org,desc in roles)+'''</div><div class="education"><div><strong>UC Santa Cruz</strong><br><span>B.S. Computer Engineering · Computer Systems · December 2026</span></div><div><strong>UC San Diego</strong><br><span>Visiting student · Computer architecture · Summer 2025</span></div></div><p class="note">Also: AM 11A group tutoring and spiking-neural-network work associated with UCSC’s Neuromorphic Computing Group.</p></section>'''
(R/'index.html').write_text(page('Engineering, writing & things I make','Harsh Ranjan — computer engineer building energy systems, embedded software and applied ML. Selected technical projects, essays, artwork and experience.','<main id="main-content">'+hero+work+writing+hobbies+experience+'</main>'))
for p in projects:
 (R/'projects').mkdir(exist_ok=True)
 credit='<p class="credit">Conceptual project illustration.</p>'
 if p['visual'] in ['solar','circuit']:credit='<p class="credit">Contextual photograph, not the project installation. <a href="../credits.html">Photo credit ↗</a></p>'
 body=f'''<main class="wrap" id="main-content"><div class="page-hero"><a class="breadcrumb" href="../index.html#work">← All projects</a><div class="eyebrow">{E(p['category'])} · {p['status']}</div><h1>{E(p['headline'])}</h1><p class="lede">{E(p['summary'])}</p></div>{visual(p,'../',True)}{credit}<div class="case-layout"><aside class="case-side"><h2>Project</h2><p>{E(p['title'])}</p><h2>Status</h2>{status(p)}<h2>Tools used</h2><ul class="tags">'''+''.join('<li>'+E(t)+'</li>' for t in p['tools'])+'''</ul></aside><div class="case-body"><section><h2>The problem</h2><p>'''+E(p['problem'])+'''</p></section><section><h2>How I approached it</h2>'''+''.join('<p>'+E(t)+'</p>' for t in p['approach'])+'''</section><section class="result"><h2>What changed</h2>'''+''.join('<p>'+E(t)+'</p>' for t in p['result'])+'''</section><p class="note">'''+E(p['note'])+'</p>'
 if p['id']=='microgrid-manager':body+=f'<a class="back-link" href="{ARTICLE}">Read our LF Edge article ↗</a>'
 if p.get('technical'):
  body+='<section class="technical-details"><h2>Engineering decisions</h2>'+''.join('<p>'+rich(t)+'</p>' for t in p['technical'])+'</section>'
 if p.get('related'):
  body+='<div class="related-reading"><span class="eyebrow">Related reflection</span>'+''.join(f'<a href="../writing/{id}.html">{E(next(w["title"] for w in writings if w["id"]==id))} ↗</a>' for id in p['related'])+'</div>'
 body+='</div></div></main>'
 (R/'projects'/f'{p["id"]}.html').write_text(page(p['title'],p['summary'],body,'../'))
for w in writings:
 (R/'writing').mkdir(exist_ok=True)
 (R/'writing'/f'{w["id"]}.html').write_text(page(w['title'],w['summary'],essay_body(w),'../'))
collection='<main class="wrap" id="main-content"><div class="page-hero"><a class="breadcrumb" href="../index.html#writing">← Home</a><span class="eyebrow">THE WRITING COLLECTION</span><h1>Following a question<br><em>all the way through.</em></h1><p class="lede">Essays on institutions, myths and art. Reflections on building software, working together and accepting the consequences of invention.</p></div><label class="search-label" for="essay-search">Find an essay by title, theme or subject</label><input id="essay-search" class="essay-search" type="search" placeholder="Try accountability, myth, software…"><p id="essay-count" class="note" role="status" aria-live="polite">'+str(len(writings))+' essays and reflections</p><div class="essay-grid collection-grid">'+''.join('<div data-essay="'+E((w['title']+' '+w['kind']+' '+w['summary']).lower(),quote=True)+'">'+essay_card(w,'')+'</div>' for w in writings)+'</div><p id="essay-empty" hidden>No matches. Try another title or theme.</p></main>'
(R/'writing'/'index.html').write_text(page('Collected writing','Essays, discussion responses and engineering retrospectives by Harsh Ranjan.',collection,'../'))
for id,title,meta,desc in art:
 (R/'art').mkdir(exist_ok=True)
 content=art_content[id]
 gallery='<div class="art-sequence">'+''.join(f'<figure><a href="../assets/{im["src"]}" target="_blank" rel="noopener"><img src="../assets/{im["src"]}" alt="{E(title)} — archive photograph {i+1}" loading="lazy"></a><figcaption>Study {i+1:02d} <a href="../assets/{im["src"]}" target="_blank" rel="noopener">View full image ↗</a></figcaption></figure>' for i,im in enumerate(content['images']))+'</div>'
 words=''
 if content['statement']:words+='<h2>Artist statement</h2>'+prose(content['statement'])
 if content['reflection']:words+='<h2>Reflection</h2>'+prose(content['reflection'])
 body=f'<main class="wrap" id="main-content"><div class="page-hero"><a class="breadcrumb" href="../index.html#hobbies">← Art & hobbies</a><span class="eyebrow">{E(meta)} · {len(content["images"])} images</span><h1>{E(title)}</h1><p class="lede">{E(desc)}</p></div>'+gallery+'<article class="reader"><div class="essay-text">'+words+'</div><p class="reading-note">Photographs from the Project and Writing Archive. Artist statements and reflections use the Collected Essays text where available; Container Assemblage uses its original archived reflection.</p><a class="back-link" href="../index.html#hobbies">← Back to the collection</a></article></main>'
 (R/'art'/f'{id}.html').write_text(page(title,desc,body,'../'))
credits='''<main class="wrap image-credits" id="main-content"><div class="page-hero"><a class="breadcrumb" href="index.html">← Home</a><h1>Images & credits</h1><p class="lede">Original work, contextual photography and illustrations.</p></div><article class="reader"><h2>Project photographs</h2><p>Solar array: USDA photograph by David Kosling, public domain. <a href="https://commons.wikimedia.org/wiki/File:Photovoltaic_Panels_Reap_Solar_Energy_on_Farms_(20240809-USDA-RD-DCK-0329).jpg">Original image and license</a>.</p><p>Circuit board: Albert Stoynov, used under the Unsplash License. <a href="https://unsplash.com/photos/close-up-of-a-green-circuit-board-with-microchips-dXdr1RGvcoM">Original image</a> · <a href="https://unsplash.com/license">License</a>.</p><p>These are contextual photographs, not photographs of my deployed systems or boards. Images are resized for the web and cropped in project cards.</p><h2>Art and illustrations</h2><p>All 28 embedded image occurrences from the supplied project and writing archive are included across six artwork pages, including alternate views and the presentation sheet. The animated game, matrix, network and agent graphics are conceptual web illustrations.</p><h2>Design reference</h2><p>The spacious introduction and visual project collection were inspired by <a href="https://devansh.design/">Devansh Gandhi’s portfolio</a>. This site uses its own layout details, illustrations and content.</p></article></main>'''
(R/'credits.html').write_text(page('Image credits','Photo sources and original artwork credits.',credits))
(R/'assets'/'favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><rect width="48" height="48" rx="12" fill="#123858"/><text x="9" y="34" fill="#c8e7ff" font-family="Georgia" font-size="32">h.</text></svg>')
print('Built portfolio, project case studies, expanded writing collection and complete artwork galleries.')
